apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prefect.fullname" . }}-config
  namespace: {{ .Values.namespace }}  # Use the specified namespace from values.yaml
data:
  modificationTimestamp: "{{ now }}"