apiVersion: v1
kind: ConfigMap
metadata:
  name: prefect-helloflow-config
  namespace: {{ .Values.namespace }}  # Use the specified namespace from values.yaml
data:
  modificationTimestamp: "{{ now }}"