apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-flow-job-{{ randAlphaNum 5 | lower }}  # Append a random string for uniqueness
  namespace: {{ .Values.namespace }}  # Namespace set from values.yaml
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
        - name: prefect-flow-container
          image: "docker.io/nweistra/itlprefecthelloflow:{{ .Values.image.tag }}"  # Use specified Docker image
          env:
            - name: PREFECT_API_URL
              value: {{ .Values.prefect.api.url }}  # Prefect API URL from values
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Run the Prefect flow
              python /opt/prefect/flows/hello_flow.py &&
              # Update the ConfigMap with the current timestamp
              kubectl patch configmap prefect-flow-job-config -n {{ .Values.namespace }} --type merge -p '{"data":{"lastRun":"$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")"}}}' &&
              echo "Job completed and timestamp updated."
          resources:
            limits:  # Static resource limits
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
      restartPolicy: Never
